version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - REQUEST_BODY_LIMIT=50mb
      - RATE_LIMIT_MAX=100
      - CORS_ORIGIN=http://localhost:3000,http://allowed-origin.com
      - MONGODB_URL=mongodb://admin:password@mongo:27017/devops?authSource=admin
      - JWT_SECRET=sudusdcos3434fq2384fbc34r3wfwefq34t
      - JWT_EXPIRES_IN=1d
    depends_on:
      - mongo
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    command: npm start

  mongo:
    image: mongo:8.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: devops
    volumes:
      - user:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongo

volumes:
  user:
